# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mei-friend Documentation
email: goebl@mdw.ac.at, weigl@mdw.ac.at
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for mei-friend, the friendly browser-based 'last-mile' 
  editor for music encodings.
baseurl: "/help" # the subpath of your site, e.g. /blog
url: "https://mei-friend.mdw.ac.at" # the base hostname & protocol for your site, e.g. http://example.com
github_repo_url: https://github.com/mei-friend/mei-friend.github.io
github_repo_branch: main
twitter_username: sigsoundvienna
github_username:  mei-friend

# Build settings
theme: jekyll-theme-open-project
#plugins:
#  - jekyll-feed

tagline: Because examples are very important
# Used in hero unit on main page.

social:
  links:
    - https://twitter.com/sigsoundvienna
    - https://github.com/mei-friend

legal:
  name: mei-friend, Department of Music Acoustics – Wiener Klangstil (IWK), mdw – University of Music and Performing Arts Vienna
  tos_link: https://www.mdw.ac.at/netiquette/
  privacy_policy_link: https://iwk.mdw.ac.at/impressum/

permalink: /blog/:month-:day-:year-:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
